name: flappybird
description: "game made with flame engine"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flame: ^1.17.0
  flame_audio: ^2.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/audio/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Game
      fonts:
        - asset: assets/fonts/Game.ttf